In [1]:
import numpy as np


In [3]:
Z = np.array([[11,12,0],[5,1,8]])
Z

array([[11, 12,  0],
       [ 5,  1,  8]])

In [4]:
A = Z.tolist()
A

[[11, 12, 0], [5, 1, 8]]

In [5]:
A[0]

[11, 12, 0]

In [6]:
B = list(Z)
B

[array([11, 12,  0]), array([5, 1, 8])]

In [7]:
B[0]

array([11, 12,  0])

In [8]:
X = np.array([[1,2,3],[4,9,6],[0,1,0]])
X

array([[1, 2, 3],
       [4, 9, 6],
       [0, 1, 0]])

In [10]:
X.itemset(3,100)
X

array([[  1,   2,   3],
       [100,   9,   6],
       [  0,   1,   0]])

In [11]:
X.itemset((0,0), 300)
X

array([[300,   2,   3],
       [100,   9,   6],
       [  0,   1,   0]])

In [13]:
a = np.array([2,1,3,0])
a.sort()
a

array([0, 1, 2, 3])

In [14]:
x = np.array([[1,6,2], [4,0,2], [0,7,0]])
x

array([[1, 6, 2],
       [4, 0, 2],
       [0, 7, 0]])

In [15]:
np.sort(x, axis=1)

array([[1, 2, 6],
       [0, 2, 4],
       [0, 0, 7]])

In [16]:
np.sort(x, axis=0)

array([[0, 0, 0],
       [1, 6, 2],
       [4, 7, 2]])

In [27]:
A = np.array([1, 2, 3, 4, 5, 8, 11, 13, 17])
A

array([ 1,  2,  3,  4,  5,  8, 11, 13, 17])

In [28]:
B = np.diff(A)
B

array([1, 1, 1, 1, 3, 3, 2, 4])

In [29]:
C = np.diff(B)
C

array([ 0,  0,  0,  2,  0, -1,  2])

In [30]:
D = np.diff(A, n=2)
D

array([ 0,  0,  0,  2,  0, -1,  2])

In [31]:
y = np.array([1,0,2,0,6,0])
z = y.nonzero()
z

(array([0, 2, 4]),)

In [32]:
x = np.array([[1,6,2],[4,0,2],[1,7,0]])
x

array([[1, 6, 2],
       [4, 0, 2],
       [1, 7, 0]])

In [33]:
x.nonzero()

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 2, 0, 1]))

In [34]:
y = np.array([1,0,np.NaN, 0, np.NaN, 0, 9])
y

array([ 1.,  0., nan,  0., nan,  0.,  9.])

In [35]:
z = np.isnan(y)
z

array([False, False,  True, False,  True, False, False])

In [36]:
z.sum()

2

In [38]:
np.mean(z)

0.2857142857142857

In [39]:
a =np.array([[1,3,2], [4,5,2],[0,7,0]])
a

array([[1, 3, 2],
       [4, 5, 2],
       [0, 7, 0]])

In [40]:
a.repeat(2,axis=None)

array([1, 1, 3, 3, 2, 2, 4, 4, 5, 5, 2, 2, 0, 0, 7, 7, 0, 0])

In [41]:
a.repeat(2, axis=1)

array([[1, 1, 3, 3, 2, 2],
       [4, 4, 5, 5, 2, 2],
       [0, 0, 7, 7, 0, 0]])

In [42]:
a.repeat(2, axis=0)

array([[1, 3, 2],
       [1, 3, 2],
       [4, 5, 2],
       [4, 5, 2],
       [0, 7, 0],
       [0, 7, 0]])

In [44]:
x = np.array([[1,2],[3,4]])
np.repeat(x,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [45]:
np.repeat(x,[1,2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [47]:
np.repeat(x, [2,3], axis=1)

array([[1, 1, 2, 2, 2],
       [3, 3, 4, 4, 4]])

In [48]:
Y = [[9,1,7], [21,18,0], [8,1,13]]
Y

[[9, 1, 7], [21, 18, 0], [8, 1, 13]]

In [49]:
Z = np.choose([1,2,0],Y)
Z

array([21,  1,  7])

In [50]:
X = np.array([range(1,5), range(11,15), range(21,25)])
X

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24]])

In [51]:
np.choose([1,0,2,1],X)

array([11,  2, 23, 14])

In [53]:
X = np.array([range(1,7)])
X

array([[1, 2, 3, 4, 5, 6]])

In [54]:
i = [0,3,4,2,0]
A = np.take(X,i)
A

array([1, 4, 5, 3, 1])

In [55]:
Y = np.array([range(1,4), range(21,24)])
Y

array([[ 1,  2,  3],
       [21, 22, 23]])

In [57]:
i = [2, 1, 1, 0]
np.take(Y,i, axis=1)

array([[ 3,  2,  2,  1],
       [23, 22, 22, 21]])

In [59]:
i = [0,1]
C = np.take(Y, i , axis=0)
C

array([[ 1,  2,  3],
       [21, 22, 23]])