In [5]:
'''

Q1)  Please create the following NP arrays a, b c, and d;

a:
[[0 1 2 3]
 [10 11 12 13]]
[10 11 12 13]

b:
[[1 4 6 6]
 [8 3 45 2]]
 
c:
[[1,4,6,6], [8,3,45,2]]


d:
[[1 2]
 [3 4]]
 


'''

print('Q1')
import numpy as np

Q1


In [13]:
a = np.array([range(4), range(10,14)])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [14]:
b = np.arange(10,14)
b

array([10, 11, 12, 13])

In [15]:
c = np.array([[1,4,6,6], [8,3,45,2]])
c

array([[ 1,  4,  6,  6],
       [ 8,  3, 45,  2]])

In [16]:
d= np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [17]:
'''
Then write Python code to print out the following results like followings:

Joining arrays: a and c along axis = 0:

[[0 1 2 3]
 [10 11 12 13]
 [1 4 6 6]
 [8 3 45 2]]
 
'''

np.concatenate((a,c), axis=0)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [ 1,  4,  6,  6],
       [ 8,  3, 45,  2]])

In [18]:
'''
Joining arrays: a and c along axis =1:
[[0 1 2 3 1 4 6 6]
 [10 11 12 13 8 3 45 2]]
 
'''
np.concatenate((a,c), axis=1)

array([[ 0,  1,  2,  3,  1,  4,  6,  6],
       [10, 11, 12, 13,  8,  3, 45,  2]])

In [20]:
'''
Stack arrays a, b and c along axis = 0:

[[0 1 2 3]
 [10 11 12 13]
 [10 11 12 13]
 [1 4 6 6]
 [8 3 45 2]]

'''
np.vstack((a,b,c))

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [10, 11, 12, 13],
       [ 1,  4,  6,  6],
       [ 8,  3, 45,  2]])

In [21]:
'''
 
Stack arrays a, c and d along axis = 1:

[[ 0  1  2  3  1  4  6  6  1  2]
 [10 11 12 13 8 3 45 2 3 4]]
'''

np.hstack((a,c,d))


array([[ 0,  1,  2,  3,  1,  4,  6,  6,  1,  2],
       [10, 11, 12, 13,  8,  3, 45,  2,  3,  4]])

In [22]:
'''
Q2) You have defined a NP array using the following Python code
x = np.array ([range (8), range (5, 13), np.zeros (8), np.ones (8)])
In this question you need to practice how to split NP arrays, here you want to generate (print) the
following results. Please write Python codes to solve the sub-questions from [q21] to [q26].
[q21] Print x like:
[[0. 1. 2. 3. 4. 5. 6. 7.]
[5. 6. 7. 8. 9. 10. 11. 12.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]]
'''
x = np.array([range(8), range(5,13), np.zeros(8), np.ones(8)])
x

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [24]:
'''
[q22] Just print the shape of x
[q23] Get and print transposed x like:
[[0. 5. 0. 1.]
[1. 6. 0. 1.]
[2. 7. 0. 1.]
[3. 8. 0. 1.]
[4. 9. 0. 1.]
[5. 10. 0. 1.]
[6. 11. 0. 1.]
[7. 12. 0. 1.]]
'''
x.shape, x.T

((4, 8), array([[ 0.,  5.,  0.,  1.],
        [ 1.,  6.,  0.,  1.],
        [ 2.,  7.,  0.,  1.],
        [ 3.,  8.,  0.,  1.],
        [ 4.,  9.,  0.,  1.],
        [ 5., 10.,  0.,  1.],
        [ 6., 11.,  0.,  1.],
        [ 7., 12.,  0.,  1.]]))

In [30]:
'''

[q24] Split the array x with the equal-size in horizontal direction and print the first part of the array like
the followings:
The first array after equal-sized splitting x in horizontal way:
[[0. 1. 2. 3. 4. 5. 6. 7.]
[5. 6. 7. 8. 9. 10. 11. 12.]]

[q25] Split the array x with the equal-size in horizontal direction and print the second part of the array
like:
The second array after equal-sized splitting x in horizontal way:
[[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]]


'''
Y = np.split(x, 2, axis=0)
Y[0], Y[1]


(array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]))

In [31]:
'''

[q26] Split the array x with the equal-size in vertical direction and print two parts of the array like:
The first array after equal-sized splitting x in vertical way:
[[0. 1. 2. 3.]
[5. 6. 7. 8.]
[0. 0. 0. 0.]
[1. 1. 1. 1.]]
The second array after equal-sized splitting x in vertical way:
[[4. 5. 6. 7.]
[9. 10. 11. 12.]
[0. 0. 0. 0.]
[1. 1. 1. 1.]]
'''
Z = np.split(x, 2, axis=1)
Z[0], Z[1]

(array([[0., 1., 2., 3.],
        [5., 6., 7., 8.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]]), array([[ 4.,  5.,  6.,  7.],
        [ 9., 10., 11., 12.],
        [ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.]]))

In [ ]:
'''
Q3) You have defined a NP array using the following Python code:

                                         x = range(25)
                                         
In this question you need to practice how to resize NP arrays. Here you want to generate (print) the
following results. Please write Python codes to solve the sub-questions from [q31] to [q33].

[q31] Print the array x like:

x is
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

'''

In [ ]:
'''
Q3) You have defined a NP array using the following Python code:

                                         x = range(25)
                                         
In this question you need to practice how to resize NP arrays. Here you want to generate (print) the
following results. Please write Python codes to solve the sub-questions from [q31] to [q33].

[q31] Print the array x like:

x is
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 

 
[q32] Resize the array x into two dimensional NP array y with the 5*5 shape and print like:

The resized array x by 5*5 is
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
'''

In [34]:
X = np.array([range(25)])
X = np.resize(X, (5,5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
X.ndim

2

In [ ]:
'''
[q33] Calculate the sum of the array y based on 1) column-wise 2) row-wise 3) total and print like:

Total column-wise sum of array is
 [10 35 60 85 110]
Total row-wise sum of array is
 [50 55 60 65 70]
Total sum 
 300
 
'''

In [38]:
column_sum = np.sum(X, axis=1)
print("Total column-wise sum of array is ", column_sum)


Total column-wise sum of array is  [ 10  35  60  85 110]


In [39]:
row_sum = np.sum(X, axis=1)
print("Total row-wise sum of array is ", row_sum)


Total row-wise sum of array is  [ 10  35  60  85 110]


In [40]:
print("Total sum ", np.sum(X))

Total sum  300


In [42]:
'''
Q4) You have defined a NP arrays x and y using the following Python code:

                                         x = np.arange(25)
                                         y = np.array ([[2, 34, 6, 7], np.ones (4)])
                                         
In this question you need to practice how to resize and delete NP arrays. Here you want to generate (print) 
the following results. Please write Python codes to solve questions from [q41] to [q44].



[q41] Print the arrays x and y:

x is 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23  24]
y is 
 [[2. 34. 6. 7.]
 [1. 1. 1. 1.]]
 
 '''
x = np.arange(25)
y = np.array ([[2, 34, 6, 7], np.ones (4)])
print("x is \n", x)
print("y is \n", y)

x is 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
y is 
 [[ 2. 34.  6.  7.]
 [ 1.  1.  1.  1.]]


In [50]:
x = np.arange(25)

In [51]:
''' 
[q42] Apply the method delete() on x at index = 5 without specifying axis option and print the result like:

The outcome after flattening (delete without specifying axis option): 

 [0 1 2 3 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

'''
result = np.delete(x,5)
result

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [56]:
'''

 
[q42] Apply the method delete() on x at index = 5 without specifying axis option and print the result like:

The outcome after flattening (delete without specifying axis option): 

 [0 1 2 3 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 
[q43] Apply the method np.resize() on x with the 5*5 outcome shape, and delete at column 
index = 5 (by specifying axis option) and print the result like:

The resized array x is: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The outcome after the deletion of the third column is: 
 [[0 1 3 4]
 [5 6 8 9]
 [10 11 13 14]
 [15 16 18 19]
 [20 21 23 24]]
 
'''

x = np.resize(x, (5,5))
print(x)
new = np.delete(x,2,axis=1)
new

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  3,  4],
       [ 5,  6,  8,  9],
       [10, 11, 13, 14],
       [15, 16, 18, 19],
       [20, 21, 23, 24]])

In [ ]:
'''
[q44] Apply the method np.resize() on x with the 5*5 outcome shape, and delete at row 
index = 3 (by specifying axis option) and print the result like:

The outcome after the deletion of the third row is: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 '''

In [58]:
new = np.delete(x,2, axis=0)
new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
'''
Q5) You have defined a NP arrays x and y using the following Python code:

                                         import numpy as np 
                                         x= np.arange(24)                         
                                         
In this question you first resize the array x into a two dimensional array as below:

                                      [[ 0  1  2  3  4  5  6  7  8  9 10 11]
                                      [12 13 14 15 16 17 18 19 20 21 22 23]]
                                      
Then you generate (print) the following results. Please write Python codes to solve the questions [q51] to [q53]
[q51] Use resize method to transpose x into 2*12 shape (inplace operation) and print:

The resized array x is 
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19 20 21 22 23]]

'''
x = np.arange(24)
x.resize(2,12)
x
#y = np.resize(x,(2,12))
#y


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
'''

[q52] Use reshape method to transpose x into 3*8 new array y and print y (non-inplace operation) and print like:

The reshaped array y is 
 [[0 1 2 3 4 5 6 7]
 [8 9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
The array x is 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
 
[q53] Print the number of dimensions of y using ‘ndim’ property like:

The number of dimensions in y is 
 2


'''

In [67]:
y = np.reshape(x, (3,8))
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [66]:
y.ndim

2

In [70]:
'''
Q6) Write Python codes to solve the following questions:

  [q61] Return and print the default OS directory
  [q62] Change (reset) the default OS directory to your own folder (choose your preferred directory)
  [q63] Create and print the following NP array ‘x’ using Python codes:
  
[[5. 2. 7. 4.]
[3. 4. 5. 6.]
[1. 1. 1. 1.]
[0. 0. 0. 0.]]

   [q64] Use the indexing method (fancy indexing) to extract diagonal elements from the NP 
         array ‘x’ and store the results into a new array ‘y’  
   [q65] Save the array ‘y’ into an external file under the default OS directory
   [q66] Load the external file into a NP array ‘z’ and print ‘z‘

'''
import os
os.getcwd()

'/Users/sadichha/UdacityClasses/UdemyClass/CompletePythonForDataScienceAndCloud/myRepo/PythonForDataScienceAndCloudComputing'

In [71]:
os.chdir(r'/Users/sadichha/UdacityClasses/UdemyClass/CompletePythonForDataScienceAndCloud/myRepo/')
os.getcwd()

'/Users/sadichha/UdacityClasses/UdemyClass/CompletePythonForDataScienceAndCloud/myRepo'

In [72]:
os.chdir(r'/Users/sadichha/UdacityClasses/UdemyClass/CompletePythonForDataScienceAndCloud/myRepo/PythonForDataScienceAndCloudComputing')
os.getcwd()

'/Users/sadichha/UdacityClasses/UdemyClass/CompletePythonForDataScienceAndCloud/myRepo/PythonForDataScienceAndCloudComputing'

In [74]:
x = np.array([[5,2,7,4], range(3,7), np.ones(4), np.zeros(4)])
x

array([[5., 2., 7., 4.],
       [3., 4., 5., 6.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [76]:
np.array([range(4), range(4)])

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [75]:
y = x[range(4), range(4)]
y

array([5., 4., 1., 0.])

In [77]:
np.save('savearray',y)

In [78]:
type(y)

numpy.ndarray

In [79]:
z = np.load('savearray.npy')
z

array([5., 4., 1., 0.])

In [81]:
'''
Q7)

Q71) Print the ranking order of the items in the array ‘draw’.

Q72) Print the ranking order of the constant ‘cut’ in the array ‘draw’ if you place it in this array.

Q73) Assuming the array ‘draw’ contains the results for each ‘drawn value’ after you have done
20 times drawing experiment. If the ‘drawn value‘ is greater than the value of ‘cut’, then the reward
is obtained from the array ‘reward’ at the corresponding time experiment (i.e. based on the same index
of the array ‘reward’ as that of ‘draw’), otherwise the penalty is received from the array 
‘penalty’ at the corresponding experiment (i.e. based on the same index of the array ‘penalty’ as 
that of ‘draw’). Please calculate the mean value of return after these 20 drawing experiments.
'''
import numpy as np
draw = np.random.ranf(size=20)
reward = np.arange(20)*10
penalty = -1*np.arange(2, 22)*10
cut = 0.38

print ('The ranking order of draw is ', np.argsort(draw))
print ('the ranking order for ' +str(cut) +" in draw is ", np.searchsorted(draw, cut))
amount = np.where(draw > cut, reward, penalty)
print (amount)
print (amount.mean())

The ranking order of draw is  [16 10  3  7 14 12  5  1  9 18 13  2 17  4  0 15  8  6 19 11]
the ranking order for 0.38 in draw is  11
[   0   10   20  -50   40   50   60   70   80   90 -120  110  120  130
  140  150 -180  170  180  190]
63.0


In [83]:
'''
Q8)

Q81) Read the data from the file classification.csv into a Numpy array ‘csvdata’

Q82) Create x = np.array ([[90, 96], [70, 130], [130, 80], [103, 73], [82, 135], [100, 100]]), check the shape

Q83) Find the mean of the np array ‘csvdata’ 

Q84) Separate the np array ‘csvdata’ into two np arrays (corresponding to two classes or
groups data), one (array calss1) is for the last item in each record being 0 and other (array calss2)
is for  the last item in each record being 1. Then calculate the mean for each split array to generate
two centers (np array).

Q85) Classify the items in the array x into two classes based on its weighted distance to two centers.
Note, the weight here is the inversed number of observations in each class (corresponding to the arrays class1 and class2)


'''
import numpy as np
csvdata = np.loadtxt('classification.csv', delimiter=',')
csvdata

array([[ 75., 117.,   0.],
       [ 92., 113.,   0.],
       [ 94.,  77.,   1.],
       ...,
       [ 77., 122.,   0.],
       [ 78.,  51.,   1.],
       [ 79.,  93.,   1.]])

In [136]:
x = np.array([[90, 96], [70, 130], [130, 80], [103, 73], [82, 135], [100, 100]])
x, x.shape

(array([[ 90,  96],
        [ 70, 130],
        [130,  80],
        [103,  73],
        [ 82, 135],
        [100, 100]]), (6, 2))

In [137]:
np.mean(csvdata, axis=0)

array([ 87.47769231, 100.58769231,   0.38461538])

In [138]:
csvdata[:,-1]

array([0., 0., 1., ..., 0., 1., 1.])

In [139]:
class1= csvdata[np.where(1 == csvdata[:,-1])]
class1

array([[ 94.,  77.,   1.],
       [116.,  40.,   1.],
       [106.,  60.,   1.],
       ...,
       [113.,  74.,   1.],
       [ 78.,  51.,   1.],
       [ 79.,  93.,   1.]])

In [140]:
class2= csvdata[np.where(0 == csvdata[:,-1])]
class2

array([[ 75., 117.,   0.],
       [ 92., 113.,   0.],
       [ 91., 118.,   0.],
       ...,
       [ 82., 116.,   0.],
       [ 96., 106.,   0.],
       [ 77., 122.,   0.]])

In [141]:
np.mean(class1, axis=0)

array([100.286,  69.146,   1.   ])

In [142]:
np.mean(class2, axis=0)

array([ 79.4725 , 120.23875,   0.     ])

In [143]:

center1 = class1.mean(axis=0)[0:2]
center2 = class2.mean(axis=0)[0:2]
num1 = len(class1)
num2 = len(class2)

def distance(p1, p2):
    return (np.sqrt(sum((p1-p2)**2)))

def classify(p, center1, center2):
    dis1 = distance(p, center1)
    dis2 = distance(p, center2)
    if dis1 * (1/num1) <= dis2*(1/num2):
        return 'class1'
    else:
        return 'class2'
    
for j in range(x.shape[0]):
    class_type = classify(x[j], center1, center2)
    print(x[j], 'is the class of ', class_type)

[90 96] is the class of  class2
[ 70 130] is the class of  class2
[130  80] is the class of  class1
[103  73] is the class of  class1
[ 82 135] is the class of  class2
[100 100] is the class of  class2


In [124]:
calss1 = csvdata[np.where((1 == csvdata[:][:,2]))]
calss2 = csvdata[np.where((0 == csvdata[:][:,2]))]
print(calss1)
print(calss2)
print (calss1.mean(axis=0))
print (calss2.mean(axis=0))

[[ 94.  77.   1.]
 [116.  40.   1.]
 [106.  60.   1.]
 ...
 [113.  74.   1.]
 [ 78.  51.   1.]
 [ 79.  93.   1.]]
[[ 75. 117.   0.]
 [ 92. 113.   0.]
 [ 91. 118.   0.]
 ...
 [ 82. 116.   0.]
 [ 96. 106.   0.]
 [ 77. 122.   0.]]
[100.286  69.146   1.   ]
[ 79.4725  120.23875   0.     ]


In [115]:
x = np.array([[5,2,7,4], range(3,7), np.ones(4), np.zeros(4)])
print(x)
x[1:3][:,2:]


[[5. 2. 7. 4.]
 [3. 4. 5. 6.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


array([[5., 6.],
       [1., 1.]])

In [126]:
np.mean(x, axis=0)

array([2.25, 1.75, 3.25, 2.75])

In [116]:
x[:,:3]

array([[5., 2., 7.],
       [3., 4., 5.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [117]:
x[:,1:]

array([[2., 7., 4.],
       [4., 5., 6.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [118]:
x[:,0]

array([5., 3., 1., 0.])

In [119]:
x[:,-1]

array([4., 6., 1., 0.])

In [120]:
x[1:3,1:3]

array([[4., 5.],
       [1., 1.]])