First Run ‘import Numpy as np’, then finish the following questions:

Q1) Create a Numpy Array ‘X’ that contains the sequential number from 1 to 100.


Then calculate the statistics and solve the following questions

a) Mean value of elements in ‘X’

b) Summed value of elements in ‘X’

c) Number of elements in ‘X’

d) Create a new Numpy Array ‘Y’, with each element of ‘Y’ being the square root of element at the same
array index.

e) Create a new Numpy Array ‘Z’, with each element being the difference between two consecutive
elements in Array ‘X’. For example,

Z[0] =X[1] - X[0]

f) X+X/2

In [1]:
import numpy as np
X = np.array([range(1,101)])
X

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [3]:
np.mean(X), np.sum(X), X.size

(50.5, 5050, 100)

In [4]:
Y = [i**(1/2) for i in X]
Y

[array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
         2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
         3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
         4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
         4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
         5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558,
         5.56776436,  5.65685425,  5.74456265,  5.83095189,  5.91607978,
         6.        ,  6.08276253,  6.164414  ,  6.244998  ,  6.32455532,
         6.40312424,  6.4807407 ,  6.55743852,  6.63324958,  6.70820393,
         6.78232998,  6.8556546 ,  6.92820323,  7.        ,  7.07106781,
         7.14142843,  7.21110255,  7.28010989,  7.34846923,  7.41619849,
         7.48331477,  7.54983444,  7.61577311,  7.68114575,  7.74596669,
         7.81024968,  7.87400787,  7.93725393,  8.        ,  8.06225775,
         8.1240384 ,  8.18535277,  8.24621125,  8.3

In [6]:
Z = np.diff(X)
Z

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [7]:
Z2 = X + X/2
Z2

array([[  1.5,   3. ,   4.5,   6. ,   7.5,   9. ,  10.5,  12. ,  13.5,
         15. ,  16.5,  18. ,  19.5,  21. ,  22.5,  24. ,  25.5,  27. ,
         28.5,  30. ,  31.5,  33. ,  34.5,  36. ,  37.5,  39. ,  40.5,
         42. ,  43.5,  45. ,  46.5,  48. ,  49.5,  51. ,  52.5,  54. ,
         55.5,  57. ,  58.5,  60. ,  61.5,  63. ,  64.5,  66. ,  67.5,
         69. ,  70.5,  72. ,  73.5,  75. ,  76.5,  78. ,  79.5,  81. ,
         82.5,  84. ,  85.5,  87. ,  88.5,  90. ,  91.5,  93. ,  94.5,
         96. ,  97.5,  99. , 100.5, 102. , 103.5, 105. , 106.5, 108. ,
        109.5, 111. , 112.5, 114. , 115.5, 117. , 118.5, 120. , 121.5,
        123. , 124.5, 126. , 127.5, 129. , 130.5, 132. , 133.5, 135. ,
        136.5, 138. , 139.5, 141. , 142.5, 144. , 145.5, 147. , 148.5,
        150. ]])

Q2) Create a tuple T= (3, 4, 2, 6, np.NaN, 7), then solve the following questions:


a) Create a Boolean NP Array ‘X’ that contains TRUE if the element in ‘T’ is nonzero, otherwise the value
is FALSE (using 'dtype=np.bool ')


b) Create a float NP Array ‘Y’ from the tuple ‘T’ (using 'dtype = np.float ')


c) Return a Boolean Numpy Array ‘Z’ that contains TRUE if the element in ‘T’ is missing, otherwise the
value is FALSE


d) Calculate the total number of missing values in the tuple ‘Y’ based on the NP array ‘Z’ created in c).


e) Sort the NP Array ‘Y’ in ascending order


f) Return the data type of the NP Array ‘Y’

In [8]:
T = (3, 4, 2, 6, np.NaN, 7)
T

(3, 4, 2, 6, nan, 7)

In [20]:
X = np.array([i != 0 for i in T])
X

array([ True,  True,  True,  True,  True,  True])

In [23]:
Y = np.array(T, dtype=float)
Y

array([ 3.,  4.,  2.,  6., nan,  7.])

In [24]:
T = np.array(T)
Z = np.isnan(T)
Z

array([False, False, False, False,  True, False])

In [25]:
np.sum(Z)

1

In [26]:
np.sort(Y)

array([ 2.,  3.,  4.,  6.,  7., nan])

In [29]:
Y.dtype

dtype('float64')

Q3) Create the following list or tuple objects (run python codes) first:

(1) A = (1, 3, 5, 9, 11, 18) (2) B = list(range (1, 7)) (3) C = [7] * 6

Solve the following questions:

a) Create a multidimensional (row=3, column=6) Numpy Array ‘M’ using above data objects.

b) Return the dimension and shape of the Numpy Array ‘M’.

c) Get a Numpy Array ‘T’ by transposing ‘M’.

d) Create an identical Numpy Array ‘G’ to ‘M’.

e) Return the total number of elements in ‘M’.

In [31]:
A = (1, 3, 5, 9, 11, 18) 
B = list(range (1, 7))
C = [7] * 6
A, B, C

((1, 3, 5, 9, 11, 18), [1, 2, 3, 4, 5, 6], [7, 7, 7, 7, 7, 7])

In [35]:
M = np.vstack((A, B, C))
M

array([[ 1,  3,  5,  9, 11, 18],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  7,  7,  7,  7,  7]])

In [36]:
M.ndim, M.shape

(2, (3, 6))

In [37]:
T = M.T
T

array([[ 1,  1,  7],
       [ 3,  2,  7],
       [ 5,  3,  7],
       [ 9,  4,  7],
       [11,  5,  7],
       [18,  6,  7]])

In [39]:
G = M.copy()
G


array([[ 1,  3,  5,  9, 11, 18],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  7,  7,  7,  7,  7]])

In [41]:
M.size

18

Q4) Given the Python list [0, 1, 2, 3, 4], use some NP functions to generate the following np arrays
respectively:


1) np.array([0 0 0 1 1 1 2 2 2 3 3 3 4 4 4])


2) np.array([0 1 2 3 4 0 1 2 3 4 0 1 2 3 4])

In [52]:
X =np.array([range(5)])
X.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [53]:
X.repeat(3, axis=0).flatten()

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [54]:
np.tile(X,3)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

Q5) First produce a two dim np array:
[[ 1 2 3 4 5 6 7 8 9 10] [10 9 8 7 6 5 4 3 2 1]]

Then use the NP array's repeat() function to generate the following arrays:

1) [[ 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10] [10 10 9 9 8 8 7 7 6 6 5 5 4 4 3 3 2 2 1 1]]

2) [[ 1 2 3 4 5 6 7 8 9 10]
 [ 1 2 3 4 5 6 7 8 9 10]
 [10 9 8 7 6 5 4 3 2 1]
 [10 9 8 7 6 5 4 3 2 1]]

In [66]:
X = np.array([range(1,11), range(10,0,-1)])
X, X.ndim

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [10,  9,  8,  7,  6,  5,  4,  3,  2,  1]]), 2)

In [69]:
np.repeat(X, 2, axis=1)

array([[ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
         9,  9, 10, 10],
       [10, 10,  9,  9,  8,  8,  7,  7,  6,  6,  5,  5,  4,  4,  3,  3,
         2,  2,  1,  1]])

In [70]:
np.repeat(X, 2, axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

Q6) Use the Numpy functions: zeros(), ones() and a python list [True, False, True] to
    
a) Create 3 Numpy arrays

b) Merge them into a one dim NP array like:
[0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1.]

c) Shuffle the NP array using the shuffle() function

d) Use the np's certain functions to calculate the % of ones, and # of zeros in the shuffled array

In [97]:
X = np.array([np.zeros(3), np.ones(3), [True, False, True]])
x1 = np.zeros(3)
x2 = np.ones(5)
x3 = [True, False, True]
X = np.concatenate((x1,x2,x3),axis=0)
X

array([0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1.])

In [98]:
np.random.shuffle(X)
print(X)

[0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0.]


In [99]:
100* list(X).count(1)/X.size

63.63636363636363

In [103]:
X.sum()/X.size *100

63.63636363636363

In [105]:
X.size - X.sum()

4.0

Q7) Use the list L = [3, 6, 0, 2, 0, 2, 1, 0] to define a NP array 'v'. 

Then use a NP's function to return the
indices of non-zero items and save these indices into a NP array. Then use

1) The array slicing method to extract non-zero values in the np array ‘v’, what is the shape of the
resulting array?

2) The take() function to extract those non-zero values in the np array ‘v’, what is the shape of the
resulting array?

In [107]:
L = [3, 6, 0, 2, 0, 2, 1, 0] 
v = np.array(L)
v

array([3, 6, 0, 2, 0, 2, 1, 0])

In [108]:
non_zero_ind = np.nonzero(v)
non_zero_ind

(array([0, 1, 3, 5, 6]),)

In [111]:
v[non_zero_ind], v[non_zero_ind].shape

(array([3, 6, 2, 2, 1]), (5,))

In [113]:
np.take(v, non_zero_ind), np.take(v, non_zero_ind).shape

(array([[3, 6, 2, 2, 1]]), (1, 5))