In [1]:
import numpy as np


In [3]:
Y=np.array([range(1,5), (2,3,4,0), range(2,6)])
Y

array([[1, 2, 3, 4],
       [2, 3, 4, 0],
       [2, 3, 4, 5]])

In [4]:
A=Y[0:2,:]

B=Y[0:2,0:2]

C=Y[:,0:3]
print('Y:' , Y)
print ('A:' , A)
print ('B:' , B)
print ('C:' , C)

Y: [[1 2 3 4]
 [2 3 4 0]
 [2 3 4 5]]
A: [[1 2 3 4]
 [2 3 4 0]]
B: [[1 2]
 [2 3]]
C: [[1 2 3]
 [2 3 4]
 [2 3 4]]


In [16]:
X = np.array([range(1,11)])
print(X)
A = (X>4)
print("A == ", A)
B = (X>4) | (X<9)
print("B == ", B)


[[ 1  2  3  4  5  6  7  8  9 10]]
A ==  [[False False False False  True  True  True  True  True  True]]
B ==  [[ True  True  True  True  True  True  True  True  True  True]]


In [22]:
X = np.array([range(1,7)]) ** 2
Y = np.array([range(7,13)])
A = (X>Y)
B = (X==Y)
print("X == ", X)
print("Y == ", Y)
print("A === ", A, " X[A] == ", X[A])
print("B == ", B, " X[B] == ", X[B])


X ==  [[ 1  4  9 16 25 36]]
Y ==  [[ 7  8  9 10 11 12]]
A ===  [[False False False  True  True  True]]  X[A] ==  [16 25 36]
B ==  [[False False  True False False False]]  X[B] ==  [9]


In [33]:
X = np.array(range(1,25))
Y = X[[1,3,0,12]]
print(X)
print("Y == ", Y)
X.resize(6,4)
print(X)
Y = X[[2,1,0],[0,3,1]]
Y

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Y ==  [ 2  4  1 13]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


array([9, 8, 2])

In [35]:
X = np.array(range(1,17)).reshape((4, 4))

print (X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [39]:
X[[1,2,0,3],:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [34]:
# fancy index examples:

X = np.array(range(1,17)).reshape((4, 4))

print (X)

print ('--------------------------------------------------')

print (X[[1, 2, 0, 3],:][[1]])

print ('--------------------------------------------------')

print (X[[1, 2, 0, 3]][[1],:])

print ('--------------------------------------------------')

print (X[[0, 1, 2, 3]][:,[1, 2]])

print ('--------------------------------------------------')

print (X[[0, 3, 1, 1]][[1, 2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------------------------------------
[[ 9 10 11 12]]
--------------------------------------------------
[[ 9 10 11 12]]
--------------------------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
--------------------------------------------------
[[13 14 15 16]
 [ 5  6  7  8]]


In [47]:
X = np.array([range(1,5), np.zeros(4), (1,2,1,2)])
print(X)

[[1. 2. 3. 4.]
 [0. 0. 0. 0.]
 [1. 2. 1. 2.]]


In [48]:
A = X.ravel()
A

array([1., 2., 3., 4., 0., 0., 0., 0., 1., 2., 1., 2.])

In [49]:
B = X.flatten()
B

array([1., 2., 3., 4., 0., 0., 0., 0., 1., 2., 1., 2.])

In [50]:
A[1] = 100
X

array([[  1., 100.,   3.,   4.],
       [  0.,   0.,   0.,   0.],
       [  1.,   2.,   1.,   2.]])

In [52]:
B[3] = 100
print(B)
print(X)

[  1.   2.   3. 100.   0.   0.   0.   0.   1.   2.   1.   2.]
[[  1. 100.   3.   4.]
 [  0.   0.   0.   0.]
 [  1.   2.   1.   2.]]


In [53]:
X = np.array([range(1,5), np.zeros(4), (1,2,1,2)])
X

array([[1., 2., 3., 4.],
       [0., 0., 0., 0.],
       [1., 2., 1., 2.]])

In [54]:
A = X.transpose()
A

array([[1., 0., 1.],
       [2., 0., 2.],
       [3., 0., 1.],
       [4., 0., 2.]])

In [55]:
B = X.T
B

array([[1., 0., 1.],
       [2., 0., 2.],
       [3., 0., 1.],
       [4., 0., 2.]])

In [56]:
A[2,2] = 100
A

array([[  1.,   0.,   1.],
       [  2.,   0.,   2.],
       [  3.,   0., 100.],
       [  4.,   0.,   2.]])

In [57]:
X

array([[  1.,   2.,   3.,   4.],
       [  0.,   0.,   0.,   0.],
       [  1.,   2., 100.,   2.]])

In [58]:
B[2,2] = -9
B

array([[ 1.,  0.,  1.],
       [ 2.,  0.,  2.],
       [ 3.,  0., -9.],
       [ 4.,  0.,  2.]])

In [59]:
X

array([[ 1.,  2.,  3.,  4.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  2., -9.,  2.]])

In [67]:
X = np.array(range(1,13))
Y = np.array(range(1,13))
Z = X
X, Y


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [68]:
A = X.reshape(3,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
Y .resize(3,4)
Y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
X.shape = (2,6)
X

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [71]:
Z

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [72]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
Y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
#stacking up arrays
X = np.array([range(1,5)]).reshape(2,2)
X

array([[1, 2],
       [3, 4]])

In [80]:
Y = np.array([range(3,7)]).reshape(2,2)
Y

array([[3, 4],
       [5, 6]])

In [81]:
np.concatenate((X, Y), axis=0)

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [83]:
np.vstack((X,Y))

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [84]:
#horizontal stacking
X = np.array([range(2,6)]).reshape(2,2)
X

array([[2, 3],
       [4, 5]])

In [86]:
Y = np.array([range(4,8)]).reshape(2,2)
Y

array([[4, 5],
       [6, 7]])

In [87]:
np.concatenate((X,Y), axis=1)

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [88]:
np.hstack((X,Y))

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [89]:
X = np.array([range(1,5)])
Y = np.array([range(4,8)])
X, Y

(array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]]))

In [90]:
np.row_stack((X,Y))

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [91]:
np.column_stack((X,Y))

array([[1, 2, 3, 4, 4, 5, 6, 7]])

In [92]:
##split
Z = np.array([range(1,5), range(3,7)])
Z

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [93]:
print(Z)
Z.shape

[[1 2 3 4]
 [3 4 5 6]]


(2, 4)

In [94]:
np.split(Z,4,axis=1)

[array([[1],
        [3]]), array([[2],
        [4]]), array([[3],
        [5]]), array([[4],
        [6]])]

In [96]:
np.hsplit(Z,4)

[array([[1],
        [3]]), array([[2],
        [4]]), array([[3],
        [5]]), array([[4],
        [6]])]

In [97]:
np.vsplit(Z,2)

[array([[1, 2, 3, 4]]), array([[3, 4, 5, 6]])]

In [98]:
np.split(Z, 2, axis=0)

[array([[1, 2, 3, 4]]), array([[3, 4, 5, 6]])]