In [1]:
import numpy as np


In [3]:
Y=np.array([range(1,5), (2,3,4,0), range(2,6)])
Y

array([[1, 2, 3, 4],
       [2, 3, 4, 0],
       [2, 3, 4, 5]])

In [4]:
A=Y[0:2,:]

B=Y[0:2,0:2]

C=Y[:,0:3]
print('Y:' , Y)
print ('A:' , A)
print ('B:' , B)
print ('C:' , C)

Y: [[1 2 3 4]
 [2 3 4 0]
 [2 3 4 5]]
A: [[1 2 3 4]
 [2 3 4 0]]
B: [[1 2]
 [2 3]]
C: [[1 2 3]
 [2 3 4]
 [2 3 4]]


In [16]:
X = np.array([range(1,11)])
print(X)
A = (X>4)
print("A == ", A)
B = (X>4) | (X<9)
print("B == ", B)


[[ 1  2  3  4  5  6  7  8  9 10]]
A ==  [[False False False False  True  True  True  True  True  True]]
B ==  [[ True  True  True  True  True  True  True  True  True  True]]


In [22]:
X = np.array([range(1,7)]) ** 2
Y = np.array([range(7,13)])
A = (X>Y)
B = (X==Y)
print("X == ", X)
print("Y == ", Y)
print("A === ", A, " X[A] == ", X[A])
print("B == ", B, " X[B] == ", X[B])


X ==  [[ 1  4  9 16 25 36]]
Y ==  [[ 7  8  9 10 11 12]]
A ===  [[False False False  True  True  True]]  X[A] ==  [16 25 36]
B ==  [[False False  True False False False]]  X[B] ==  [9]


In [33]:
X = np.array(range(1,25))
Y = X[[1,3,0,12]]
print(X)
print("Y == ", Y)
X.resize(6,4)
print(X)
Y = X[[2,1,0],[0,3,1]]
Y

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Y ==  [ 2  4  1 13]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


array([9, 8, 2])

In [35]:
X = np.array(range(1,17)).reshape((4, 4))

print (X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [39]:
X[[1,2,0,3],:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [42]:
print(X[[1,2,0,3],:][[1]])

[[ 9 10 11 12]]


In [43]:
print (X[[1, 2, 0, 3]][[1],:])

[[ 9 10 11 12]]


In [44]:
print (X[[1, 2, 0, 3]][:,[1,2]])

[[ 6  7]
 [10 11]
 [ 2  3]
 [14 15]]


In [45]:
print (X[[0, 3, 1, 1]][[1, 2]])

[[13 14 15 16]
 [ 5  6  7  8]]


In [34]:
# fancy index examples:

X = np.array(range(1,17)).reshape((4, 4))

print (X)

print ('--------------------------------------------------')

print (X[[1, 2, 0, 3],:][[1]])

print ('--------------------------------------------------')

print (X[[1, 2, 0, 3]][[1],:])

print ('--------------------------------------------------')

print (X[[0, 1, 2, 3]][:,[1, 2]])

print ('--------------------------------------------------')

print (X[[0, 3, 1, 1]][[1, 2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------------------------------------
[[ 9 10 11 12]]
--------------------------------------------------
[[ 9 10 11 12]]
--------------------------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
--------------------------------------------------
[[13 14 15 16]
 [ 5  6  7  8]]
