In [1]:
import numpy as np

In [2]:
csvdata = np.loadtxt('classification.csv', delimiter=',')
csvdata

array([[ 75., 117.,   0.],
       [ 92., 113.,   0.],
       [ 94.,  77.,   1.],
       ...,
       [ 77., 122.,   0.],
       [ 78.,  51.,   1.],
       [ 79.,  93.,   1.]])

In [3]:
x = np.array([[90, 96], [70, 130], [130, 80], [103, 73], [82, 135], [100, 100]])
x, x.shape

(array([[ 90,  96],
        [ 70, 130],
        [130,  80],
        [103,  73],
        [ 82, 135],
        [100, 100]]), (6, 2))

In [7]:
np.mean(csvdata)

62.81666666666667

In [9]:
np.mean(csvdata, axis=0)

array([ 87.47769231, 100.58769231,   0.38461538])

In [11]:
class1 = csvdata[:, -1]
class1

array([0., 0., 1., ..., 0., 1., 1.])

In [13]:
class2 = csvdata[:, :-1]
class2

array([[ 75., 117.],
       [ 92., 113.],
       [ 94.,  77.],
       ...,
       [ 77., 122.],
       [ 78.,  51.],
       [ 79.,  93.]])

In [14]:
class1 = csvdata[np.where(csvdata[:,-1] == 1)]
class1

array([[ 94.,  77.,   1.],
       [116.,  40.,   1.],
       [106.,  60.,   1.],
       ...,
       [113.,  74.,   1.],
       [ 78.,  51.,   1.],
       [ 79.,  93.,   1.]])

In [16]:
class2 = csvdata[np.where(csvdata[:,-1] == 0)]
class2

array([[ 75., 117.,   0.],
       [ 92., 113.,   0.],
       [ 91., 118.,   0.],
       ...,
       [ 82., 116.,   0.],
       [ 96., 106.,   0.],
       [ 77., 122.,   0.]])

In [18]:
class3 = csvdata[np.where(csvdata[:,0] <= 90)]
class3

array([[ 75., 117.,   0.],
       [ 83., 116.,   0.],
       [ 73., 110.,   0.],
       ...,
       [ 77., 122.,   0.],
       [ 78.,  51.,   1.],
       [ 79.,  93.,   1.]])

In [19]:
class4 = csvdata[np.where(csvdata[:,0] >=100)]
class4

array([[116.,  40.,   1.],
       [106.,  60.,   1.],
       [110.,  44.,   1.],
       [115.,  90.,   1.],
       [128.,  68.,   1.],
       [132.,  70.,   1.],
       [114.,  62.,   1.],
       [103.,  26.,   1.],
       [117.,  47.,   1.],
       [105., 114.,   1.],
       [102.,  69.,   1.],
       [114.,  66.,   1.],
       [111.,  72.,   1.],
       [102.,  91.,   1.],
       [125.,  59.,   1.],
       [102.,  38.,   1.],
       [103., 124.,   0.],
       [115.,  84.,   1.],
       [134., 100.,   1.],
       [106., 130.,   0.],
       [102.,  52.,   1.],
       [102.,  95.,   1.],
       [105.,  42.,   1.],
       [102.,  73.,   1.],
       [129.,  91.,   1.],
       [131.,  76.,   1.],
       [105.,  93.,   1.],
       [110.,  98.,   1.],
       [107., 107.,   0.],
       [103.,  78.,   1.],
       [110.,  50.,   1.],
       [106., 101.,   1.],
       [102.,  41.,   1.],
       [139.,  56.,   1.],
       [105.,  68.,   1.],
       [129.,  60.,   1.],
       [112.,  95.,   1.],
 

In [20]:
class1 = csvdata[np.where(csvdata[:,-1] == 1)]
class0 = csvdata[np.where(csvdata[:,-1] == 0)]
class0, class1

(array([[ 75., 117.,   0.],
        [ 92., 113.,   0.],
        [ 91., 118.,   0.],
        ...,
        [ 82., 116.,   0.],
        [ 96., 106.,   0.],
        [ 77., 122.,   0.]]), array([[ 94.,  77.,   1.],
        [116.,  40.,   1.],
        [106.,  60.,   1.],
        ...,
        [113.,  74.,   1.],
        [ 78.,  51.,   1.],
        [ 79.,  93.,   1.]]))

In [21]:
x

array([[ 90,  96],
       [ 70, 130],
       [130,  80],
       [103,  73],
       [ 82, 135],
       [100, 100]])

In [35]:
center1 = np.mean(class1, axis=0)[:2]
center0 = np.mean(class2, axis=0)[:2]

def distance(x1, x2):
    return (np.sqrt(sum((x1 - x2)**2)))

def classify(p, center0, center1):
    dis1 = distance(p, center1)
    dis0 = distance(p, center0)
    if dis1 * (1/(len(class1))) <= dis0 * (1/(len(class0))):
        return 'class1'
    else:
        return 'class2'
    
for i in range(len(x)):
    print(x[i] , classify(x[i], center0, center1))


[90 96] class2
[ 70 130] class2
[130  80] class1
[103  73] class1
[ 82 135] class2
[100 100] class2


len(class1)

In [36]:
import pandas as pd

In [37]:
x = pd.DataFrame([pd.Series([0,-2,7,3]), pd.Series([0,0,1,-3])])
x

0  1  2  3
0  0 -2  7  3
1  0  0  1 -3

In [45]:
Y = pd.DataFrame(np.array([range(1,5), [0,1,2,0]]))
Y

0  1  2  3
0  1  2  3  4
1  0  1  2  0

In [41]:



Y = pd.DataFrame(np.array([range(1,5), [0,1,2,0]]))
Y

0  1  2  3
0  1  2  3  4
1  0  1  2  0

In [41]:
Y = pd.DataFrame(np.array([range(1,5), [0,1,2,0]]))
Y

0  1  2  3
0  1  2  3  4
1  0  1  2  0

In [47]:
z = pd.DataFrame(np.array([[0,0,1,8],[6,1,0,0]]), columns=['c1', 'c2', 'c3', 'c4'])
z

c1  c2  c3  c4
0   0   0   1   8
1   6   1   0   0

In [48]:
records = np.array([['Prakash', 'Bhatta', 'M', 30], ['Sadichha', 'Sitauls','F', 30], ['Rabin', 'Neupane', 'M', 25]])
records

array([['Prakash', 'Bhatta', 'M', '30'],
       ['Sadichha', 'Sitauls', 'F', '30'],
       ['Rabin', 'Neupane', 'M', '25']], dtype='<U8')

In [49]:
x = pd.DataFrame(records, columns=['FName', 'LName', 'Sex', 'Age'])
x

FName    LName Sex Age
0   Prakash   Bhatta   M  30
1  Sadichha  Sitauls   F  30
2     Rabin  Neupane   M  25

In [50]:
x.ndim, x.shape, x.size, len(x)

(2, (3, 4), 12, 3)

In [51]:
x.values

array([['Prakash', 'Bhatta', 'M', '30'],
       ['Sadichha', 'Sitauls', 'F', '30'],
       ['Rabin', 'Neupane', 'M', '25']], dtype=object)

In [52]:
x.columns

Index(['FName', 'LName', 'Sex', 'Age'], dtype='object')

In [53]:
x.index

RangeIndex(start=0, stop=3, step=1)

In [54]:
x.axes[0]

RangeIndex(start=0, stop=3, step=1)

In [55]:
x.axes[1]

Index(['FName', 'LName', 'Sex', 'Age'], dtype='object')

In [68]:
x = np.array(range(1,5))
y = np.array(['A', 'B', 'C','D'])
z = np.array(['True', 'False', 'True','False'])
k = np.random.random(size=4)
x , y , z, k

(array([1, 2, 3, 4]),
 array(['A', 'B', 'C', 'D'], dtype='<U1'),
 array(['True', 'False', 'True', 'False'], dtype='<U5'),
 array([0.85322538, 0.29053975, 0.90888465, 0.08891695]))

In [70]:
import pandas as pd
df = pd.DataFrame({'key1':x, 'key2':y, 'key3':z, 'key4':k}, index=['a', 'b','c','d'])
df

key1 key2   key3      key4
a     1    A   True  0.853225
b     2    B  False  0.290540
c     3    C   True  0.908885
d     4    D  False  0.088917

In [87]:
df = pd.read_csv('people_miss.csv', na_values='NaN')

df1 = pd.read_csv('people_miss.csv', na_values='NaN', header=None)
df1

0         1                          2    3          4       5      6  \
0   id      name                      email  age  entrydate  gender  spend   
1    1      glen            glent@gmail.com   23   19650409       M    462   
2    2   Yinging        yirmic302@gmail.com   24   20070611       F    215   
3    3    Lendor         kude1035@gmail.com   45   19900905       M    185   
4    4   Rickina           RK023781@aol.com   24   19850110       F    800   
5    5   Tomocro    troman.telcon@gmail.com  NaN   19970819       M     46   
6    6     Keren    tl.nesleeza@hotmail.com   58   19550902       M   1000   
7    7  Mafammia         mafuupink@yahoo.ca   28   19611127       F    338   
8    8      Lina  Lina.centen1023@gmail.com   42   19970303       M    185   
9    9    Cather        clarkying@yahoo.com   33   19851101       M    554   
10  10     Kelvn      chimecll.lx@gmail.com   45   19921026       M     31   
11  20     David        linta8892@gmail.com   63   19951012       M    108   
12  12   Tomocro    troman.telcon@gmail.com  NaN   19970819       M     46   
13  13       NaN      yantming056@yahoo.com   38   19810608       F    NaN   
14  14     Kelvn      chimecll.lx@gmail.com   23   19921026       M     89   
15   6     Keren    tl.nesleeza@hotmail.com   58   19550902       M   1000   
16  15     David    denniel7008@hotmail.com   70   19900908       M    554   
17  16      Mike          Mk03723@gmail.com   23   20050322       M    185   
18   4   Rickina           RK023781@aol.com   24   19850110       F    800   
19  18      Mike          MMKK023@gmail.com  NaN   20051205       M    538   
20  19     Zenik          Mufa.li@yahoo.com   27   19721201       M     15   
21  20     Marry        hes.kui@hotmail.com   58   19720822       F    723   
22  21     Tanko          Tank0923@yahoo.ca   28   20010304       M      0   
23  22  Emamakee       Kookder231@gmail.com   42   19960309       F    400   
24  23       NaN       minko12945@yahoo.com   33   19330413       M    923   
25  24     Qxian        c9012@kirkoland.com   45   19911213       F    NaN   
26  25      John         Yue30189@gmail.com   63   20060610       M    600   
27  26   Flighte        Filiwwe1987@IBM.com   38   19780922       F    462   
28  27    Kamber       Boao3321@hotmail.com   70   20111119       M    169   

             7        8          9  
0   upperlimit   income  education  
1          714  23113.3          U  
2          571    20000          C  
3         1000    72000          U  
4          714        0          H  
5          857    35000          C  
6          429        0          U  
7          NaN    90000          H  
8          429      NaN          U  
9          571    80000          C  
10         714    22000          U  
11         857    42999          H  
12         857    35000          C  
13         429        0        NaN  
14         714     5900          U  
15         429        0          U  
16         714    21000          H  
17         286    40000          H  
18         714        0          H  
19         857    89000          C  
20         857    31000          C  
21         429    43000          C  
22           0        0          C  
23         571    52900          H  
24         714    40000          U  
25         571    52000          U  
26         571    76000          C  
27         714        0          C  
28         571   170000          H

In [88]:
import numpy as np 
import pandas as pd

In [89]:
df = pd.read_csv('people_miss.csv', na_values='NA', usecols=['id','spend','education'])
df

id   spend education
0    1   462.0         U
1    2   215.0         C
2    3   185.0         U
3    4   800.0         H
4    5    46.0         C
5    6  1000.0         U
6    7   338.0         H
7    8   185.0         U
8    9   554.0         C
9   10    31.0         U
10  20   108.0         H
11  12    46.0         C
12  13     NaN       NaN
13  14    89.0         U
14   6  1000.0         U
15  15   554.0         H
16  16   185.0         H
17   4   800.0         H
18  18   538.0         C
19  19    15.0         C
20  20   723.0         C
21  21     0.0         C
22  22   400.0         H
23  23   923.0         U
24  24     NaN         U
25  25   600.0         C
26  26   462.0         C
27  27   169.0         H

In [90]:
df = pd.read_csv('people_miss.csv', na_values='NA', header=None)
df

0         1                          2    3          4       5      6  \
0   id      name                      email  age  entrydate  gender  spend   
1    1      glen            glent@gmail.com   23   19650409       M    462   
2    2   Yinging        yirmic302@gmail.com   24   20070611       F    215   
3    3    Lendor         kude1035@gmail.com   45   19900905       M    185   
4    4   Rickina           RK023781@aol.com   24   19850110       F    800   
5    5   Tomocro    troman.telcon@gmail.com  NaN   19970819       M     46   
6    6     Keren    tl.nesleeza@hotmail.com   58   19550902       M   1000   
7    7  Mafammia         mafuupink@yahoo.ca   28   19611127       F    338   
8    8      Lina  Lina.centen1023@gmail.com   42   19970303       M    185   
9    9    Cather        clarkying@yahoo.com   33   19851101       M    554   
10  10     Kelvn      chimecll.lx@gmail.com   45   19921026       M     31   
11  20     David        linta8892@gmail.com   63   19951012       M    108   
12  12   Tomocro    troman.telcon@gmail.com  NaN   19970819       M     46   
13  13       NaN      yantming056@yahoo.com   38   19810608       F    NaN   
14  14     Kelvn      chimecll.lx@gmail.com   23   19921026       M     89   
15   6     Keren    tl.nesleeza@hotmail.com   58   19550902       M   1000   
16  15     David    denniel7008@hotmail.com   70   19900908       M    554   
17  16      Mike          Mk03723@gmail.com   23   20050322       M    185   
18   4   Rickina           RK023781@aol.com   24   19850110       F    800   
19  18      Mike          MMKK023@gmail.com  NaN   20051205       M    538   
20  19     Zenik          Mufa.li@yahoo.com   27   19721201       M     15   
21  20     Marry        hes.kui@hotmail.com   58   19720822       F    723   
22  21     Tanko          Tank0923@yahoo.ca   28   20010304       M      0   
23  22  Emamakee       Kookder231@gmail.com   42   19960309       F    400   
24  23       NaN       minko12945@yahoo.com   33   19330413       M    923   
25  24     Qxian        c9012@kirkoland.com   45   19911213       F    NaN   
26  25      John         Yue30189@gmail.com   63   20060610       M    600   
27  26   Flighte        Filiwwe1987@IBM.com   38   19780922       F    462   
28  27    Kamber       Boao3321@hotmail.com   70   20111119       M    169   

             7        8          9  
0   upperlimit   income  education  
1          714  23113.3          U  
2          571    20000          C  
3         1000    72000          U  
4          714        0          H  
5          857    35000          C  
6          429        0          U  
7          NaN    90000          H  
8          429      NaN          U  
9          571    80000          C  
10         714    22000          U  
11         857    42999          H  
12         857    35000          C  
13         429        0        NaN  
14         714     5900          U  
15         429        0          U  
16         714    21000          H  
17         286    40000          H  
18         714        0          H  
19         857    89000          C  
20         857    31000          C  
21         429    43000          C  
22           0        0          C  
23         571    52900          H  
24         714    40000          U  
25         571    52000          U  
26         571    76000          C  
27         714        0          C  
28         571   170000          H

In [91]:
# use dictionary to produce data frame
name = [np.nan, 'Mary', 'Kate']
age = [14, 30, None]
df6 = pd.DataFrame({'name':name, 'age':age})
df6.head()

name   age
0   NaN  14.0
1  Mary  30.0
2  Kate   NaN

In [95]:
X = pd.read_csv("special.csv", na_values=".", encoding='latin1')
X

id                                            Address  price
0   1  122 NDSAY BLVD                                ...  400.0
1   2  8 FLETTHE@RD CREEK BLVD                       ...  334.2
2   3  2100 FOLLEGE WAY                              ...    NaN
3   4                        222 WINDKIRK ?DR   APT 206     NaN
4   5  33 ISLEW@OTE AVE                              ...   55.2
5   6                                   194 WHINT ? AVE    78.3
6   7  111 BER@TRAIL CRES                            ...    NaN
7   8  11  €SKTEWART ST                              ...   93.0

In [96]:
X.Address = X.Address.str.replace('\n', '')
X.Address = X.Address.str.replace('@', '')

In [97]:
X

id                                            Address  price
0   1  122 NDSAY BLVD                                ...  400.0
1   2  8 FLETTHERD CREEK BLVD                        ...  334.2
2   3  2100 FOLLEGE WAY                              ...    NaN
3   4                        222 WINDKIRK ?DR   APT 206     NaN
4   5  33 ISLEWOTE AVE                               ...   55.2
5   6                                   194 WHINT ? AVE    78.3
6   7  111 BERTRAIL CRES                             ...    NaN
7   8  11  €SKTEWART ST                              ...   93.0

In [100]:
df = pd.read_csv('replace_special.csv')
df

Unnamed: 0  id                                            Address  price
0           0   1  122 NDSAY BLVD                                ...  400.0
1           1   2  8 FLETTHERD CREEK BLVD                        ...  334.2
2           2   3  2100 FOLLEGE WAY                              ...    NaN
3           3   4                         222 WINDKIRK DR   APT 206     NaN
4           4   5  33 ISLEWOTE AVE                               ...   55.2
5           5   6                                    194 WHINT  AVE    78.3
6           6   7  111 BERTRAIL CRES                             ...    NaN
7           7   8  11  €SKTEWART ST                              ...   93.0

In [104]:
df.price = df.price.fillna(0)
df

Unnamed: 0  id                                            Address  price
0           0   1  122 NDSAY BLVD                                ...  400.0
1           1   2  8 FLETTHERD CREEK BLVD                        ...  334.2
2           2   3  2100 FOLLEGE WAY                              ...    0.0
3           3   4                         222 WINDKIRK DR   APT 206     0.0
4           4   5  33 ISLEWOTE AVE                               ...   55.2
5           5   6                                    194 WHINT  AVE    78.3
6           6   7  111 BERTRAIL CRES                             ...    0.0
7           7   8  11  €SKTEWART ST                              ...   93.0

In [105]:
df.price

0    400.0
1    334.2
2      0.0
3      0.0
4     55.2
5     78.3
6      0.0
7     93.0
Name: price, dtype: float64

In [107]:
df.price = df.price.map(str)
df.price

0    400.0
1    334.2
2      0.0
3      0.0
4     55.2
5     78.3
6      0.0
7     93.0
Name: price, dtype: object

In [109]:
df.price = df.price + '99'
df

Unnamed: 0  id                                            Address  \
0           0   1  122 NDSAY BLVD                                ...   
1           1   2  8 FLETTHERD CREEK BLVD                        ...   
2           2   3  2100 FOLLEGE WAY                              ...   
3           3   4                         222 WINDKIRK DR   APT 206    
4           4   5  33 ISLEWOTE AVE                               ...   
5           5   6                                    194 WHINT  AVE    
6           6   7  111 BERTRAIL CRES                             ...   
7           7   8  11  €SKTEWART ST                              ...   

       price  
0  400.09999  
1  334.29999  
2    0.09999  
3    0.09999  
4   55.29999  
5   78.39999  
6    0.09999  
7   93.09999

In [110]:
df.price = df.price.map(float)
df.price

0    400.09999
1    334.29999
2      0.09999
3      0.09999
4     55.29999
5     78.39999
6      0.09999
7     93.09999
Name: price, dtype: float64

In [117]:
df = pd.read_csv("replace_special.csv", na_values='NaN')
df.price = df.price.fillna(0)
df

Unnamed: 0  id                                            Address  price
0           0   1  122 NDSAY BLVD                                ...  400.0
1           1   2  8 FLETTHERD CREEK BLVD                        ...  334.2
2           2   3  2100 FOLLEGE WAY                              ...    0.0
3           3   4                         222 WINDKIRK DR   APT 206     0.0
4           4   5  33 ISLEWOTE AVE                               ...   55.2
5           5   6                                    194 WHINT  AVE    78.3
6           6   7  111 BERTRAIL CRES                             ...    0.0
7           7   8  11  €SKTEWART ST                              ...   93.0

In [123]:
df.price = df.price.map(str) + '99'

In [124]:
df.price

0    499.099
1    433.299
2     99.099
3     99.099
4    154.299
5    177.399
6     99.099
7    192.099
Name: price, dtype: object

In [125]:
df.price = df.price.map(float)
df.price

0    499.099
1    433.299
2     99.099
3     99.099
4    154.299
5    177.399
6     99.099
7    192.099
Name: price, dtype: float64

In [127]:
x = pd.DataFrame(np.arange(10).reshape(5,2), columns=list('AB'))
x

A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [128]:
y = pd.DataFrame(np.arange(10).reshape(5,2), columns=['A', 'B'])
y

A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [144]:
df = y
#df.A = df.A.map(str)
df = df.applymap(str)




In [145]:
df = df + df
df

A   B
0  00  11
1  22  33
2  44  55
3  66  77
4  88  99

In [150]:
df.A = df.A.map(float)
df.A

0     0.0
1    22.0
2    44.0
3    66.0
4    88.0
Name: A, dtype: float64